# Generated by Django 5.0.4 on 2024-05-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_ease', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
