# Generated by Django 5.0.4 on 2024-05-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_ease', '0002_rename_phone_contact_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=255)),
                ('Phonenumber', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
                ('IsPending', models.BooleanField(default=True)),
            ],
        ),
    ]
